/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package nest.app

import nest.clojure.Util

@Suppress("PLATFORM_CLASS_MAPPED_TO_KOTLIN", "UNCHECKED_CAST")
fun main() {
    println("Hello, world")

    val question: Object = Util.read("(+ 41 1)")
    println("Question " + question + " class " + question.getClass())
    println("Answer " + Util.eval(question))
}
